### PR TITLE
GlobalR/GlobalRX/GlobalRY Gates

### PR DESCRIPTION
**Pull request by GenericP3rson**
Adding support for the GlobalR/RX/RY General Gates as layers, similar to the [GlobalR Gates](https://qiskit.org/documentation/_modules/qiskit/circuit/library/generalized_gates/gr.html) from Qiskit

### CODE REVIEW

**Comment by Hanrui-Wang** [comment]
great to see the Global rot gates! could you add tests for those three gates?

**Comment by GenericP3rson** [comment]
Finally have some notable progress! Turns out that my circuit was correct, I just had an aliasing issue. The gates be good now!

**Comment by GenericP3rson** [comment]
I don’t really know why 3.7 is consistently failing with a syntax error at `import torchquantum as tq`. It could be something to look into, but 3.7 has hit end-of-life, I’m not too concerned about it.

**Review by Hanrui-Wang — APPROVED** [review]
reviewed

**Comment by Hanrui-Wang** [comment]
Thank you [GenericP3rson](https://github.com/GenericP3rson) for your contributions! I will merge it.

**Pull request merged**
