### PR TITLE
Adding more gates, for issue #134

### PR DESCRIPTION
**Pull request by pandey-tushar**
Added 9 more gates

### CODE REVIEW

**Comment by pandey-tushar** [comment]
@Hanrui-Wang I have some questions about the argument class of the existing classes in the operators file. Can I reach out to you on the Unitary Fund discord server?

**Comment by Hanrui-Wang** [comment]
Thank you @pandey-tushar  and @dhanvi-bharadwaj  for the contributions!

**Comment by pandey-tushar** [comment]
Hi @Hanrui-Wang . We didn't get enough time to update the n_local.py file, so the Ansatz and layers might not work. However, I believe the other functions should work. The errors in the commit is for the n_local files only right?

**Comment by dhanvi-bharadwaj** [comment]
> Thank you @pandey-tushar and @dhanvi-bharadwaj for the contributions!

Hi @Hanrui-Wang , thanks for the quick reply. Can you also assign me the issue on the main repo? Thanks for the help.

**Pull request merged**
