### PR TITLE
Reformatting NLocal Circuit

### PR DESCRIPTION
**Pull request by GenericP3rson**
Similar to https://github.com/mit-han-lab/torchquantum/pull/187, breaking NLocal layers into separate layers.

### CODE REVIEW

**Review by Hanrui-Wang — APPROVED** [review]
reviewed

**Comment by Hanrui-Wang** [comment]
Is this PR ready to merge? I think we need add some tests to the functions.

**Comment by GenericP3rson** [comment]
Gotcha, I’ll go ahead and add some tests!

**Comment by GenericP3rson** [comment]
Just as an FYI, I ended up deviating from comparing the unitaries for these NLocal layers and instead checked if the gates were correct since the NLocal circuits extend BlueprintCircuits in Qiskit and both use parameters. (This is a bit of a todo for me to dive a bit deeper into the comparison of a TQ parameter and Qiskit Parameter.) I have a ton of different configurations for TwoLocal tested and a few for the others. 

Something we can discuss next time is formatting choices. Currently, the NLocal circuits take as input an architecture dictionary (similar to the other layers), but Qiskit just takes in the wires. I think this change should be fine to make. In addition, Qiskit’s NLocal circuits are actual circuits whereas ours are layers which can be applied to circuits.

**Comment by Hanrui-Wang** [comment]
Thank you [GenericP3rson](https://github.com/GenericP3rson) for your contributions!

**Pull request merged**
