### PR TITLE
Bug Fixes and Full Standard Gates

### PR DESCRIPTION
**Pull request by GenericP3rson**
Same as https://github.com/mit-han-lab/torchquantum/pull/180 without the formatting fixes.

### CODE REVIEW

**Comment by GenericP3rson** [comment]
Updated XXPlusYY, ECR, CH, iSWAP, DCX, CSX, R, and C3X gates to pass tests.

**Comment by GenericP3rson** [comment]
Added gates from https://github.com/mit-han-lab/torchquantum/pull/164/, https://github.com/mit-han-lab/torchquantum/pull/167/, https://github.com/mit-han-lab/torchquantum/pull/170, and https://github.com/mit-han-lab/torchquantum/pull/172/.

**Review by Hanrui-Wang — APPROVED** [review]
reviewed

**Comment by Hanrui-Wang** [comment]
Thank you [GenericP3rson](https://github.com/GenericP3rson) for the contributions! PR Merged!

**Pull request merged**
