### PR TITLE
Authenticate IBM Quantum account with GH actions to run unit tests

### PR DESCRIPTION
**Pull request by SaashaJoshi**
This PR builds a GH actions workflow that runs unit tests while authenticating the IBM Quantum account with the help of an `IBM_API_TOKEN` stored as a GH secret. It partially addresses #261. 

The changes aim to run the `tests/plugin/test_qiskit_plugins.py` file with GH actions.

### CODE REVIEW

**Comment by GenericP3rson** [comment]
Hi, just wanted to let you know that you don’t need to worry about getting the lint + pre-commit passing.

**Comment by SaashaJoshi** [comment]
Thanks for letting me know. I was indeed worried about the linting.

**Comment by SaashaJoshi** [comment]
Hey @GenericP3rson, the latest GH workflow gives the following error,

'''cli
FAILED test/plugin/test_qiskit_plugins.py::test_expval_observable - qiskit_ibm_runtime.accounts.exceptions.AccountNotFoundError: 'Unable to find account.'
'''

Just wanted to make sure that we use the same keyword for the GH secret, which is `IBM_API_TOKEN'. Let me know if this is different and I will reflect those changes in the code. If this is not causing the error, I will brainstorm more.

**Comment by SaashaJoshi** [comment]
Okay, the `AccountNotFound` error persists. I am not sure what is going wrong here. I am able to run the tests successfully on my local machine though. I even have a PR on my fork of `torchquantum` and the tests pass there. For reference, check [this](https://github.com/SaashaJoshi/torchquantum/pull/1)

**Comment by GenericP3rson** [comment]
Hi, so sorry, I have not yet added the secret yet; I don’t have the permissions to add secrets to this repo at the moment but will get it added ASAP!

While I’m getting that sorted, to fully complete the task, if you want to add a set of tests for some function (either as a separate PR or with this), that would be great!

**Comment by SaashaJoshi** [comment]
No problem!
Absolutely, I will add a few test classes to increase the coverage.

**Review by Hanrui-Wang — APPROVED** [review]

**Review by GenericP3rson — APPROVED** [review]

**Pull request merged**
